[plugins]
"rocks.nvim" = "2.47.2"
"rocks-config.nvim" = "3.1.2"
"rocks-dev.nvim" = "1.8.1"
"rocks-git.nvim" = "2.5.8"
"rocks-treesitter.nvim" = "1.3.1"
"rocks-edit.nvim" = "scm"
"luasnip" = "2.4.1"

"neorg" = "9.3.0"
"neorg-archive" = "1.1.0"
"neorg-interim-ls" = "2.1.1"
# "neorg-query" = "1.4.0"
"neorg-worklog" = "1.3.4"

"nvim-thyme" = "1.6.1"
"which-key.nvim" = "3.17.0"
"lualine.nvim" = "scm"
"nvim-dap" = "0.10.0"
"nvim-dap-ui" = "scm"
"nvim-lspconfig" = "2.5.0"
"rustaceanvim" = "7.1.1"
"nvim-parinfer" = "scm"
"nvim-ts-autotag" = "scm"
tree-sitter-json = "0.0.37"
tree-sitter-javascript = "0.0.41"
tree-sitter-toml = "0.0.31"
tree-sitter-bash = "0.0.50"
tree-sitter-css = "0.0.39"
tree-sitter-comment = "0.0.33"
tree-sitter-diff = "0.0.33"
tree-sitter-gitignore = "0.0.29"
tree-sitter-graphql = "0.0.29"
tree-sitter-html = "0.0.40"
tree-sitter-markdown = "0.0.46"
tree-sitter-markdown_inline = "0.0.44"
tree-sitter-nix = "0.0.69"
tree-sitter-lua = "0.0.40"
tree-sitter-python = "0.0.56"
tree-sitter-rust = "0.0.56"
tree-sitter-sql = "0.0.51"
tree-sitter-svelte = "0.0.33"
tree-sitter-tsx = "0.0.37"
tree-sitter-typescript = "0.0.38"
tree-sitter-typst = "0.0.38"
tree-sitter-jsonc = "0.0.29"
tree-sitter-yaml = "0.0.37"
tree-sitter-norg = "0.2.6"
tree-sitter-norg-meta = "0.1.0"
"conform.nvim" = "9.1.0"
"helpview.nvim" = "2.1.2"
nvim-treesitter-context = "scm"
"plenary.nvim" = "0.1.4"
"snacks.nvim" = "scm"
"package-info.nvim" = "scm"
"flash.nvim" = "2.1.0"
"nvim-web-devicons" = "0.100"
tree-sitter-clojure = "0.0.32"
tree-sitter-fennel = "0.0.36"
tree-sitter-cpp = "0.0.49"
# tree-sitter-scheme = "scm"  # dev channel broken

[plugins."catppuccin"]
git = "catppuccin/nvim"
rev = "v1.11.0"

[plugins."lazydev.nvim"]
git = "folke/lazydev.nvim"
rev = "v1.10.0"

[plugins."blink.cmp"]
git = "Saghen/blink.cmp"
rev = "v1.8.0"

[plugins."blink.compat"]
git = "Saghen/blink.compat"
rev = "v2.5.0"

[plugins."blink.indent"]
git = "Saghen/blink.indent"
rev = "v2.1.2"


[plugins."neorg-templates"]
git = "pysan3/neorg-templates"
rev = "v2.0.3"


[plugins."ts-comments.nvim"]
git = "folke/ts-comments.nvim"
rev = "v1.5.0"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v2.0.0"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
rev = "v3.0.0"

[plugins."cmp-npm"]
git = "David-Kunz/cmp-npm"
rev = "2337f109f51a09297596dd6b538b70ccba92b4e4"

[plugins."neorg-contexts"]
git = "max397574/neorg-contexts"
rev = "8ae58b646700b8bc2d3bc1346c96835ceb71d884"

[plugins."nvim-paredit"]
git = "julienvincent/nvim-paredit"
rev = "v1.2.0"

[plugins."fyler.nvim"]
git = "A7Lavinraj/fyler.nvim"
rev = "15b4b1fae0b967820e0000692f17f7988bc4ebc9"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.10.0"

[bundles.neorg]
items = [
  "neorg",
  "neorg-archive",
  "neorg-contexts",
  "neorg-interim-ls",
  # "neorg-query",
  "neorg-templates",
]

[bundles.blink]
items = ["blink.cmp", "blink.compat", "cmp-npm", "luasnip"]

[bundles.lsp]
items = ["lsp_lines.nvim", "nvim-lspconfig"]

[bundles.treesitter]
items = ["nvim-treesitter-context", "nvim-ts-autotag"]

[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[treesitter.parser_map]
lisp = "fennel"

[config]
auto_setup = true
colorscheme = "catppuccin"

[config.options]
cursorline = true
expandtab = true
foldlevelstart = 99
guifont = "MonoLisa Nerd Font"
number = true
shiftwidth = 2
smartindent = true
tabstop = 2
timeout = true
timeoutlen = 300
equalalways = false
winborder = "rounded"
winwidth = 10
winminwidth = 10
