name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  check-x86-linux:
    name: Check x86_64-linux configs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [desktop, eink, pocket]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Build ${{ matrix.config }} configuration
        run:
          nix build .#nixosConfigurations.${{ matrix.config
          }}.config.system.build.toplevel --dry-run

  check-arm-linux:
    name: Check aarch64-linux config
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Build android configuration
        run:
          nix build .#nixosConfigurations.android.config.system.build.toplevel
          --dry-run

  check-darwin:
    name: Check aarch64-darwin configs
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - type: nixos
            config: macbook
            target: darwinConfigurations.macbook.system
          - type: home-manager
            config: standalone
            target: homeConfigurations.standalone.activationPackage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Build ${{ matrix.config }} configuration
        run: nix build .#${{ matrix.target }} --dry-run

  auto-merge:
    needs: [check-x86-linux, check-arm-linux, check-darwin]
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automated')
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
